// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo6laDpv0mgRsRGRiidz1XM-1FO-K2rqM',
    appId: '1:356905042097:android:b2da066fef7ab9954d2290',
    messagingSenderId: '356905042097',
    projectId: 'gpstracker-a242d',
    storageBucket: 'gpstracker-a242d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDtOlFdmDgcstkNViYzB-kx9zvzuJD3CU',
    appId: '1:356905042097:ios:e0138bf386cfe2ff4d2290',
    messagingSenderId: '356905042097',
    projectId: 'gpstracker-a242d',
    storageBucket: 'gpstracker-a242d.appspot.com',
    iosClientId: '356905042097-0ktjvljeb57odc3b6k85ftdo0el132qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.test2',
  );
}
